### ISSUE TITLE
Meitrack Commands

### ISSUE THREAD

**Issue by sherome** [alvassin/nodejs-meiligao#3]
I try to implement the commands on meitrack devices

in the Message.js
I add

>Message.commands = {
    GET_PICTURE : '@@O48,863835020683608,D00,151021062113_C1E19.jpg,0*DB',	
};

in the Tracker.js
I add

>Tracker.prototype.getPicture = function(message) {
      this.connection.write(Message.commands.GET_PICTURE);
};

in the commands.js
I add

> tracker.getPicture(function(err, data) {
    if (err) {
      console.log('GET PICTURE ERROR: ', err);
    } else {
      console.log('GET PICTURE : ', data);
    }
  });

I can build without errors but when I try to use and send the commands

[MEITRACK_GPRS_Protocol](http://www.meitrack.com/meitrack-support/protocol/MEITRACK_GPRS_Protocol.pdf)
>Example  

GPRS Sending @@O48,353358017784062,D00,0215080432_C2E03.jpg,0*DB\r\n
GPRS Reply The example cannot be displayed because of hexadecimal characters.

I take by example the nodejs-meiligao
I'm not sure if I forget something.

please help me

**Comment by alvassin** [comment]
@sherome, it seems you are trying to use quite different protocol. This nodejs module implements Meiligao protocol, when you are trying to use Meitrack one.

**Comment by sherome** [comment]
now I had problems transmission commands to gps device
Can you help me ? Gps device does not return data

**Comment by alvassin** [comment]
@sherome could you tell me your device model?

**Comment by sherome** [comment]
T333 
http://www.meitrackusa.com/trackers/gps-vehicle-trackers/t333-3g

**Comment by alvassin** [comment]
@sherome unfortunately, I can't help you - your device does not support this protocol. It is not intended to work with this module.

**Comment by sherome** [comment]
I adapted your module. I can receive data
